//
// Created by dominik on 12/22/15.
//

#ifndef SIMULATEDANNEALING_CONFIG_H
#define SIMULATEDANNEALING_CONFIG_H

#define COOLING_FACTOR 0.98
#define WARMING_FACTOR 1.5

#endif //SIMULATEDANNEALING_CONFIG_H
